# Generated by Django 2.2.6 on 2019-10-04 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spindle_power', models.FloatField(verbose_name='Spindle net power (kW)')),
                ('max_rpm', models.PositiveIntegerField(verbose_name='Max spindle RPM (1/min)')),
                ('max_cutting_speed', models.PositiveIntegerField(verbose_name='max cutting speed (mm/min)')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flute_count', models.PositiveIntegerField(verbose_name='Flute count')),
                ('diameter', models.FloatField(verbose_name='Diameter (mm)')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kc_1_1', models.FloatField(verbose_name='kc 1.1 (N/mm^2)')),
                ('mc', models.FloatField(verbose_name='Mc')),
                ('material_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='feeds_and_speeds.MaterialClass')),
            ],
        ),
        migrations.CreateModel(
            name='CuttingSpeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_per_tooth', models.FloatField(verbose_name='Feed per Tooth (mm)')),
                ('cutting_speed', models.FloatField(verbose_name='Cutting Speed (m/min)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds_and_speeds.Material')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds_and_speeds.Tool')),
            ],
        ),
    ]
