# Generated by Django 2.2.6 on 2019-10-28 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spindle_power', models.FloatField(verbose_name='Spindle net power (kW)')),
                ('max_rpm', models.PositiveIntegerField(verbose_name='Max spindle RPM (1/min)')),
                ('max_cutting_speed', models.PositiveIntegerField(verbose_name='max cutting speed (mm/min)')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
            },
        ),
        migrations.CreateModel(
            name='MaterialClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Material Class',
                'verbose_name_plural': 'Material Classes',
            },
        ),
        migrations.CreateModel(
            name='ToolVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tool Vendor',
                'verbose_name_plural': 'Tool Vendors',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flute_count', models.PositiveIntegerField(verbose_name='Flute count')),
                ('flute_length', models.FloatField(verbose_name='Flute length (mm) (max ap)')),
                ('diameter', models.FloatField(verbose_name='Diameter (mm)')),
                ('fz_factor_at_one_ae', models.FloatField(default=1.0, verbose_name='Fz factor at 1 Ae')),
                ('vc_factor_at_one_ae', models.FloatField(default=1.0, verbose_name='Vc factor at 1 Ae')),
                ('description', models.TextField(blank=True, null=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='feeds_and_speeds.ToolVendor')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kc_1_1', models.FloatField(verbose_name='kc 1.1 (N/mm^2)')),
                ('mc', models.FloatField(verbose_name='Mc')),
                ('material_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='feeds_and_speeds.MaterialClass')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='CuttingSpeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_per_tooth', models.FloatField(verbose_name='Feed per Tooth (mm)')),
                ('cutting_speed', models.FloatField(verbose_name='Cutting Speed (m/min)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds_and_speeds.Material')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds_and_speeds.Tool')),
            ],
            options={
                'verbose_name': 'Cutting Speed',
                'verbose_name_plural': 'Cutting Speeds',
            },
        ),
        migrations.CreateModel(
            name='CuttingRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ae', models.FloatField(verbose_name='Ae (width of cut) (mm)')),
                ('ap', models.FloatField(verbose_name='Ap (depth of cut) (mm)')),
                ('cutter_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds_and_speeds.CuttingSpeeds')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds_and_speeds.Machine')),
            ],
            options={
                'verbose_name': 'Cutting Recipe',
                'verbose_name_plural': 'Cutting Recipies',
            },
        ),
    ]
