# Generated by Django 2.2.6 on 2019-10-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds_and_speeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttingrecipe',
            name='machine',
        ),
    ]
