# Generated by Django 2.2.6 on 2019-10-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds_and_speeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
