# Generated by Django 2.2.6 on 2019-10-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds_and_speeds', '0002_remove_cuttingrecipe_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active Machine'),
        ),
    ]
