# Generated by Django 2.2.6 on 2019-10-04 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds_and_speeds', '0002_auto_20191004_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='feeds_and_speeds.ToolVendor'),
        ),
    ]
